---
title: "Stat210 Final Project"
author: "Kevin Liu & Evan Zhong"
format: pdf
---
```{r read-data}
library(tidyverse)
library(dplyr)
library(tidymodels)
library(MASS)
library(nnet)
cbb <- read.csv("cbb.csv")
cbb <- cbb |> filter(!is.na(POSTSEASON)) |> 
              filter(POSTSEASON != "N/A" & !is.na(POSTSEASON))
#we only want to use the teams that make the tournament

```

```{r, message = F, warning = F}
cbbOrdinal <- polr(factor(POSTSEASON) ~ CONF + G + W + ADJOE + ADJDE + BARTHAG + EFG_O + EFG_D + TOR + TORD + ORB + DRB + FTR + FTRD + X2P_O + X2P_D + X3P_O + X3P_D + ADJ_T + WAB + SEED, data = cbb)
summary(cbbOrdinal)
```
```{r, message = F, warning = F}
cbbAug <- cbb |>
  mutate(POSTSEASON = case_when(
    POSTSEASON == "R68" ~ 68,
    POSTSEASON == "R64" ~ 64,
    POSTSEASON == "R32" ~ 32,
    POSTSEASON == "S16" ~ 16,
    POSTSEASON == "E8" ~ 8,
    POSTSEASON == "F4" ~ 4,
    POSTSEASON == "2ND" ~ 2,
    POSTSEASON == "Champions" ~ 1,
    TRUE ~ NA_integer_  # Handle any other cases or unexpected values
  ))

cbbLinear <- lm(POSTSEASON ~ CONF + G + W + ADJOE + ADJDE + BARTHAG + EFG_O + EFG_D + TOR + TORD + ORB + DRB + FTR + FTRD + X2P_O + X2P_D + X3P_O + X3P_D + ADJ_T + WAB + SEED, data = cbbAug)
summary(cbbLinear)
```







